import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/utils/Navbar";
import { PageProvider } from "@/context/PageProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={` antialiased`}>
        <PageProvider>
          <Navbar />
          {children}
        </PageProvider>
      </body>
    </html>
  );
}
